services:
  kafka:
    image: apache/kafka:3.9.2
    container_name: kafka
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  rocketmq-namesrv:
    image: apache/rocketmq:5.3.2
    container_name: rocketmq-namesrv
    command: sh mqnamesrv

  rocketmq-broker:
    image: apache/rocketmq:5.3.2
    container_name: rocketmq-broker
    depends_on:
      - rocketmq-namesrv
    environment:
      NAMESRV_ADDR: rocketmq-namesrv:9876
    command: sh mqbroker

  app:
    build: .
    container_name: sporty-assignment
    ports:
      - "8080:8080"
    depends_on:
      - kafka
      - rocketmq-broker
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      ROCKETMQ_NAME_SERVER: rocketmq-namesrv:9876
      ROCKETMQ_ENABLED: "true"
