spring:
  application:
    name: sporty-assignment
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
  sql:
    init:
      mode: always
  mvc:
    problemdetails:
      enabled: true
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: sporty-assignment
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: com.sporty.assignment.api.messaging
      auto-offset-reset: earliest

rocketmq:
  enabled: true
  name-server: localhost:9876
  producer:
    group: sporty-assignment-producer
logging:
  level:
    com.sporty.assignment: DEBUG
